### PR TITLE
GitHub support

### PR DESCRIPTION
**Pull request by divarvel**
In addition to github support itself, there's a big preliminary refactoring.

It's not done yet as issue creation is not supported yet, as well as listing closed issues.

### CODE REVIEW

**Comment by divarvel** [comment]
So, `github-rs` does not support issues creation yet, as well as listing closed issues.

I can either:
 - try to replace `github-rs` with `github-gql-rs` (which is just a wrapper around graphql calls)
 - or implement both operations in `github-rs`

**Comment by NotBad4U** [comment]
If it's not too hard, we can contribute to `github-rs` to add this operation.

**Comment by divarvel** [comment]
@NotBad4U https://github.com/mgattozzi/github-rs/pull/128

Now everything works. I'll wait and see if the github-rs PR is merged quickly.

**Comment by mgattozzi** [comment]
I pushed a new version just now numbered 0.6.1 with the PR you sent in! You shouldn't be blocked on this anymore. Feel free to add endpoints and functionality you need in the future and I'll get them in for you.

**Comment by divarvel** [comment]
Thanks a lot for the speedy answer!
If I get a better understanding of how things work I could implement more
endpoints indeed.

Le 28 déc. 2017 19:50, "Michael Gattozzi" <notifications@github.com> a
écrit :

**Pull request merged**
